services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8080:8080"
  kafka:
    container_name: kafka
    user: root
    image: quay.io/strimzi/kafka:latest-kafka-3.7.1
    volumes:
      - "./server.properties:/opt/kafka/config/kraft/server.properties"
    command:
      [
        "sh",
        "-c",
        "bin/kafka-storage.sh format -t $$(bin/kafka-storage.sh random-uuid) -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties"
      ]
    ports:
      - "9092:9092"